Updated check for multiple working folders

diff --git a/menu b/menu
--- a/menu
+++ b/menu
@@ -59,28 +59,32 @@ do
   read opt
 
   scripts/check_multiple_working
-  if [ "$?" == "1" ]
+  if [ "$?" != "1" ]
   then
-    exit 0
+    case $opt in
+      1) clear; scripts/check_rom; continue;;
+      2) scripts/do_root; continue;;
+      3) scripts/add_busybox show_help;;
+      4) scripts/disable_sounds;;
+      5) scripts/add_tether;;
+      6) scripts/do_zipalign;;
+      7) scripts/change_wipe;;
+      8) scripts/change_rom_name;;
+      9) scripts/verify_update_script; continue;;
+      10) scripts/show_rom_info;;
+      0) scripts/menu_advanced $version; continue;;
+      99) scripts/build_rom;;
+      u) scripts/about $version; continue;;
+      x) scripts/init_kitchen; clear; echo; echo "Goodbye."; echo; exit 1;;
+      *) echo "Invalid option"; continue;;
+    esac
+  else
+    if [ "$opt" == "x" ]
+    then
+      scripts/press_enter
+      clear; echo; echo "Goodbye."; echo; exit 1;
+    fi
   fi
-
-  case $opt in
-    1) clear; scripts/check_rom; continue;;
-    2) scripts/do_root; continue;;
-    3) scripts/add_busybox show_help;;
-    4) scripts/disable_sounds;;
-    5) scripts/add_tether;;
-    6) scripts/do_zipalign;;
-    7) scripts/change_wipe;;
-    8) scripts/change_rom_name;;
-    9) scripts/verify_update_script; continue;;
-    10) scripts/show_rom_info;;
-    0) scripts/menu_advanced $version; continue;;
-    99) scripts/build_rom;;
-    u) scripts/about $version; continue;;
-    x) scripts/init_kitchen; clear; echo; echo "Goodbye."; echo; exit 1;;
-    *) echo "Invalid option"; continue;;
-  esac
 
   scripts/press_enter
 
diff --git a/scripts/menu_advanced b/scripts/menu_advanced
--- a/scripts/menu_advanced
+++ b/scripts/menu_advanced
@@ -34,30 +34,34 @@ do
   read opt
 
   scripts/check_multiple_working
-  if [ "$?" == "1" ]
+  if [ "$?" != "1" ]
   then
-    exit 0
+    case $opt in
+      11) scripts/do_deodex; continue;; 
+      12) scripts/task_killer;;
+      13) scripts/add_data_app show_help;;
+      14) scripts/add_nano show_help;;
+      15) scripts/add_bash show_help;;
+      16) scripts/add_apps2sd show_help;;
+      17) scripts/add_busybox_run_parts show_help;;
+      18) scripts/add_custom_boot_anim;;
+      19) scripts/porting_tools; continue;;
+      20) scripts/boot_img_tools; continue;;   
+      21) scripts/unpack_data_img;; 
+      22) scripts/sign_apks; continue;;
+      23) scripts/update_script_convert_menu; continue;;
+      24) scripts/run_plugins; continue;;
+      99) scripts/build_rom;;
+      0) exit 1;;
+      *) echo "Invalid option"; continue;;
+    esac
+  else
+    if [ "$opt" == 0 ]
+    then
+      scripts/press_enter
+      exit 1
+    fi
   fi
-
-  case $opt in
-    11) scripts/do_deodex; continue;; 
-    12) scripts/task_killer;;
-    13) scripts/add_data_app show_help;;
-    14) scripts/add_nano show_help;;
-    15) scripts/add_bash show_help;;
-    16) scripts/add_apps2sd show_help;;
-    17) scripts/add_busybox_run_parts show_help;;
-    18) scripts/add_custom_boot_anim;;
-    19) scripts/porting_tools; continue;;
-    20) scripts/boot_img_tools; continue;;   
-    21) scripts/unpack_data_img;; 
-    22) scripts/sign_apks; continue;;
-    23) scripts/update_script_convert_menu; continue;;
-    24) scripts/run_plugins; continue;;
-    99) scripts/build_rom;;
-    0) exit 1;;
-    *) echo "Invalid option"; continue;;
-  esac
 
   scripts/press_enter
 
