Added SGS file descriptions; added menu at start

diff --git a/scripts/check_rom b/scripts/check_rom
--- a/scripts/check_rom
+++ b/scripts/check_rom
@@ -15,20 +15,62 @@
 # $2 = "kernel_only"  - if this is specified, then $1 is mandatory
 #
 
+echo
+echo "CREATE WORKING FOLDER FOR ROM"
+echo "=============================="
+echo
+echo "Ensure there is at least one ROM under the 'original_update' folder!"
+echo
+echo "Select an option:"
+echo
+echo " s - Show supported formats"
+echo " x - Abort, don't create working folder"
+echo ""
+echo "Or press Enter to continue"
+echo
+echo -n "? "
+read proceed
+  
+if [ "$proceed" == "x" ]
+then
+  echo
+  echo "Cancelled"
+  exit 1
 
-echo
-echo "Ensure there is at least one ROM under the original_update folder."
-echo "The format for each ROM must be one of the following:"
-echo 
-echo " - ZIP file for a custom ROM  (e.g. update.zip)"
-echo " - ZIP file containing *.img  (e.g. rom.zip from shipped ROM)"
-echo " - ZIP file containing shipped ROM in SYSTEM + BOOT folder format"
-echo " - system.img + boot.img      (e.g. from shipped ROM or Nandroid)"
-echo " - APP file from Huawei       (e.g. UPDATE.APP from software update)"
-echo " - TAR file containing factoryfs.img and more (e.g. SGS2 stock ROM)"
-echo " - factoryfs.img + optional cache.img/zImage  (e.g. SGS2 stock ROM)"
-echo " - Working folder made with this kitchen      (e.g. WORKING_old_rom)"
-echo
+elif [ "$proceed" == "s" ]
+then
+  echo
+  echo "----------------------------------------------------------------------"
+  echo
+  echo "The format for each ROM must be one of the following:"
+  echo
+  echo " - system.img + boot.img      (e.g. from shipped ROM or Nandroid)"
+  echo " - ZIP file for a custom ROM  (e.g. update.zip)"
+  echo " - ZIP file containing *.img  (e.g. rom.zip from shipped ROM)"
+  echo " - ZIP file containing shipped ROM in SYSTEM + BOOT folder format"
+  echo " - Working folder made with this kitchen (e.g. WORKING_old_rom)"
+  echo
+  echo " Other formats:"
+  echo 
+  echo " - factoryfs.rfs + optional cache.rfs/zImage    (e.g. SGS stock ROM)"
+  echo " - factoryfs.img + optional cache.img/zImage    (e.g. SGS2 stock ROM)"
+  echo " - TAR/ZIP file containing factoryfs.rfs + more (e.g. SGS stock ROM)"  
+  echo " - TAR/ZIP file containing factoryfs.img + more (e.g. SGS2 stock ROM)"  
+  echo " - APP file from Huawei software update         (e.g. UPDATE.APP)"
+  echo
+  echo " (SGS=Samsung Galaxy S, SGS2=Samsung Galaxy SII)" 
+  echo
+  echo "----------------------------------------------------------------------"
+  echo
+  echo -n "Press Enter to continue, or type 'x' to abort: "
+  read proceed
+  
+  if [ "$proceed" == "x" ]
+  then
+    exit 1
+  fi
+
+fi
 
 scripts/make_backup_working
 
