Added support for SGS2 file types

diff --git a/scripts/choose_rom b/scripts/choose_rom
--- a/scripts/choose_rom
+++ b/scripts/choose_rom
@@ -43,6 +43,11 @@ else
   # Check for any ZIP files in original_update
   #
   zip_cmd=`find . ! -name . -prune -type f | grep -i -m 1 \\.zip$`
+ 
+  #
+  # Check for any TAR files in original_update
+  #
+  tar_cmd=`find . ! -name . -prune -type f | grep -i -m 1 \\.tar$`
 
   #
   # Check for *.APP or *.app in original_update
@@ -56,28 +61,35 @@ else
 
   cd ..
 
-  if [ "$zip_cmd" == "" ] && [ "$app_cmd" == "" ] && [ "$wkg_cmd" == "" ]
+  if [ "$zip_cmd" == "" ] && [ "$tar_cmd" == "" ] && [ "$app_cmd" == "" ] && [ "$wkg_cmd" == "" ]
   then
 
     #
-    # Check for system.img and boot.img in original_update  
-    #
-
-    # We'll prompt for a Null boot.img if no boot.img found
-    if [ ! -e original_update/system.img ]
+    # Check for factoryfs.img (cache.img and zImage are optional)
+    #  
+    if [! -e original_update/factoryfs.img]
     then
 
-      # No system.img found, check for boot.img
+      #
+      # Check for system.img and boot.img in original_update  
+      #
 
-      if [ -e original_update/boot.img ]
+      # We'll prompt for a Null boot.img if no boot.img found
+      if [ ! -e original_update/system.img ]
       then
-        echo "Error: No original_update/system.img found"
-      else
-        echo
-        echo "Error: No ROMs found under original_update folder!"
-      fi
 
-      exit 0
+        # No system.img found, check for boot.img
+
+        if [ -e original_update/boot.img ]
+        then
+          echo "Error: No original_update/system.img found"
+        else
+          echo
+          echo "Error: No ROMs found under original_update folder!"
+        fi
+
+        exit 0
+      fi
     fi
 
   fi
@@ -85,11 +97,20 @@ else
   cd original_update
 
   grep_cmd1=`find . -maxdepth 1 -type f | grep -i \\.zip$ | sed 's/ /temp_space/g' 2>/dev/null`
-  grep_cmd2=`find system.img 2>/dev/null`
-  grep_cmd3=`find . -maxdepth 1 -type f | grep -i \\.app$ | sed 's/ /temp_space/g' 2>/dev/null`
-  grep_cmd4=`find . -maxdepth 1 -type d | grep "\./WORKING_" | sed 's/ /temp_space/g' 2>/dev/null`
+  grep_cmd2=`find . -maxdepth 1 -type f | grep -i \\.tar$ | sed 's/ /temp_space/g' 2>/dev/null`  
+  grep_cmd3=`find system.img 2>/dev/null`
+  grep_cmd4=`find . -maxdepth 1 -type f | grep -i \\.app$ | sed 's/ /temp_space/g' 2>/dev/null`
 
-  grep_cmd=`echo $grep_cmd1 $grep_cmd2 $grep_cmd3 $grep_cmd4 | sed -e 's/\.\///g' | sort -f`
+  if [ -e factoryfs.img ]
+  then
+    grep_cmd5=`find factoryfs.img 2>/dev/null`
+  else
+    grep_cmd5=
+  fi
+
+  grep_cmd6=`find . -maxdepth 1 -type d | grep "\./WORKING_" | sed 's/ /temp_space/g' 2>/dev/null`
+
+  grep_cmd=`echo $grep_cmd1 $grep_cmd2 $grep_cmd3 $grep_cmd4 $grep_cmd5 $grep_cmd6 | sed -e 's/\.\///g' | sort -f`
 
 
   count=0
@@ -111,6 +132,9 @@ else
     if [ "$filename" == "system.img" ]
     then
       filename="system.img and boot.img"
+    elif [ "$filename" == "factoryfs.img" ]
+    then
+      filename="factoryfs.img, cache.img and zImage"
     fi
 
     echo "  ($count) $filename" >> ../temp.list
@@ -158,9 +182,19 @@ then
   scripts/img_files_to_working_folder create_working $1
   exit $?
 
+elif [ "$file_chosen" == "factoryfs.img" ]
+then
+  scripts/simg_files_to_working_folder create_working $1
+  exit $?
+
 elif [ "`echo $file_chosen | grep -i \\.zip$`" != "" ] && [ ! -d "original_update/$file_chosen" ]
 then
   scripts/zip_file_to_working_folder "$file_chosen" $1
+  exit $?
+
+elif [ "`echo $file_chosen | grep -i \\.tar$`" != "" ] && [ ! -d "original_update/$file_chosen" ]
+then
+  scripts/tar_file_to_working_folder "$file_chosen" $1
   exit $?
 
 elif [ "`echo $file_chosen | grep -i \\.app$`" != "" ] && [ ! -d "original_update/$file_chosen" ]
