Check before compiling simg2img

diff --git a/scripts/simg_ext4_files_to_working_folder b/scripts/simg_ext4_files_to_working_folder
--- a/scripts/simg_ext4_files_to_working_folder
+++ b/scripts/simg_ext4_files_to_working_folder
@@ -106,17 +106,6 @@ fi
 echo
 
 
-#
-# Compile sigm2img
-#
-
-scripts/compile_simg2img
-if [ "$?" == "1" ]
-then
-  exit 1
-fi
-
-
 
 if [ "$1" == "no_create" ]
 then
@@ -125,7 +114,38 @@ else
   src_dir=original_update
 fi
 
+
 system_dir=$build_dir/system
+
+
+#
+# Compile simg2img if necessary
+#
+
+echo
+echo "Analyzing system.img.ext4 ..."
+sys_bytes=`od -A n -h -j 0 -N 6 $src_dir/system.img.ext4 | sed 's/ //g'`
+
+if [ -e $src_dir/cache.img.ext4 ]
+then
+  echo "Analyzing cache.img.ext4 ..."
+  cache_bytes=`od -A n -h -j 0 -N 6 $src_dir/system.img.ext4 | sed 's/ //g'`
+else
+  cache_bytes="000000000000"
+fi
+
+if [ "$sys_bytes" != "000000000000" ] || [ "$cache_bytes" != "000000000000" ]
+then
+  echo
+  scripts/compile_simg2img
+  if [ "$?" == "1" ]
+  then
+    exit 1
+  fi
+fi
+
+
+
 cd $system_dir
 
 # Get full path
@@ -137,19 +157,25 @@ cd ../..
 # Convert system.img.ext4 to ext4
 #
 
-echo
-echo "Converting system.img.ext4 into a format for unpacking ..."
-tools/samsung_files/simg2img_files/simg2img $src_dir/system.img.ext4 \
-  $system_dir/ext4_system.img
-
-if [ ! -e $system_dir/ext4_system.img ]
+if [ "$sys_bytes" == "000000000000" ]
 then
-  echo "Unable to unpack system.img.ext4!"
-  exit 1
+  cp $src_dir/system.img.ext4 $system_dir/ext4_system.img
+
+else 
+
+  echo
+  echo "Converting system.img.ext4 into a format for unpacking ..."
+  tools/samsung_files/simg2img_files/simg2img $src_dir/system.img.ext4 \
+    $system_dir/ext4_system.img 
+
+  if [ ! -e $system_dir/ext4_system.img ]
+  then
+    echo "Unable to unpack system.img.ext4!"
+    exit 1
+  fi
+
+  rm -rf $system_dir/system.img.ext4
 fi
-
-rm -rf $system_dir/system.img.ext4
-
 
 
 #
@@ -238,21 +264,27 @@ then
     echo
   else
 
-    #
-    # Convert cache.img.ext4 to ext4
-    #
-    echo "Unpacking cache.img.ext4 into a format for unpacking ..."
-    tools/samsung_files/simg2img_files/simg2img $src_dir/cache.img.ext4 \
-      $system_dir/ext4_cache.img
-
-    if [ ! -e $system_dir/ext4_cache.img ]
+    if [ "$cache_bytes" == "000000000000" ]
     then
-      echo "Unable to unpack cache.img.ext4!"
-      exit 1
+      cp -v $src_dir/cache.img.ext4 $system_dir/ext4_cache.img
+
+    else
+
+      #
+      # Convert cache.img.ext4 to ext4
+      #
+      echo "Converting cache.img.ext4 into a format for unpacking ..."
+      tools/samsung_files/simg2img_files/simg2img $src_dir/cache.img.ext4 \
+        $system_dir/ext4_cache.img
+
+      if [ ! -e $system_dir/ext4_cache.img ]
+      then
+        echo "Unable to unpack cache.img.ext4!"
+        exit 1
+      fi
+
+      rm -rf $system_dir/cache.img.ext4
     fi
-
-    rm -rf $system_dir/cache.img.ext4
-
 
     #
     # Extract files from ext4_cache.img
@@ -284,22 +316,31 @@ then
       # 
       # Carrier bloatware
       #
+			# (Check for multi-CSC by the presence of empty app folder)
+			#
 
       if [ -d temp_csc/system/app ]
       then
-        echo
-        echo "These are apps found in sec_csc.zip:"
-        ls temp_csc/system/app
-        echo
-        echo -n "Copy the apps to your working folder (y/n)? (default: n): "
+		
+				dir_str=`ls temp_csc/system/app`
+				
+				if [ "$dir_str" != "" ]
+				then
 
-        read do_copy
-        echo
+	        echo
+	        echo "These are the apps found in sec_csc.zip:"
+	        ls temp_csc/system/app
+	        echo
+	        echo -n "Copy the apps to your working folder (y/n)? (default: n): "
 
-        if [ "$do_copy" != "y" ]
-        then
-          rm -vrf temp_csc/system/app
-        fi
+	        read do_copy
+	        echo
+
+	        if [ "$do_copy" != "y" ]
+	        then
+	          rm -vrf temp_csc/system/app
+	        fi
+				fi
       fi
 
       rm -rf temp_csc/META-INF
